# Generated by Django 3.0.8 on 2020-07-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('lang', models.CharField(choices=[('kor', 'korean'), ('eng', 'english'), ('chn', 'chinese')], default='kor', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('guest', models.ManyToManyField(blank=True, related_name='guest', to='chat.UserInfo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='chat.UserInfo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='chat.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='chat.UserInfo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
